#!/usr/bin/bash

export JAVA_HOME="~/.sdkman/candidates/java/current/bin/java"

export SDKMAN_DIR="/home/renansmoreira/.sdkman"
[[ -s "/home/renansmoreira/.sdkman/bin/sdkman-init.sh" ]] && source "/home/renansmoreira/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


export DEVTOOLS_HOME="$HOME/projetos/devtools"
export CHROME_PATH="/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe"

function reload {
	source ~/.zshrc
}

function edit {
	vim $DEVTOOLS_HOME/cli-tools/zshrc
}

function hcs {
	bash $DEVTOOLS_HOME/cli-tools/hcs.sh $@
}
